version: '3.9'

services:

  # frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    # depends_on:
    #   - auth_service
    #   - product_service
    #   - order_service
